# https://taskfile.dev

version: '3'

tasks:
  # backend tasks
  back_run_etl_script:
    aliases: ['betl']
    desc: Run the ETL script
    dotenv: ['.env']
    cmds:
      - go run ./src/etl ./src/app/env_vars.go
  back_start:
    aliases: ['bstart']
    desc: Start the backend server
    dotenv: ['.env']
    cmds:
      - go run ./src/main.go
